### ISSUE TITLE
Cannot make predictions with loaded model : device issue.

### ISSUE THREAD

**Issue by Arkkienkeli** [nitzanlab/biolord#14]
### Report

Hi !
I have trained a model with GPU (on a custom data), then saved it to a file. 
Then I try to load the model and make predictions:
```
model.load(dir_path = '/biolord_test/model/', adata = adata, accelerator='cpu')
idx_source = np.where((adata.obs["split"] == "Training"))
adata_source = adata[idx_source].copy()
adata_preds = model.compute_prediction_adata(
    adata, adata_source, target_attributes=["cell_type"]
)
```
And get an error 
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```
I tried both ` accelerator='cpu'` and ` accelerator='gpu'` , but it did not help. 

Full stacktrace: 
```
Traceback (most recent call last):
  File "biolord_test/train.py", line 78, in <module>
    adata_preds = model.compute_prediction_adata(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/biolord/_model.py", line 889, in compute_prediction_adata
    predictions_dict, _ = self._compute_prediction(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/biolord/_model.py", line 857, in _compute_prediction
    pred, _ = self.module.get_expression(dataset_comb)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/biolord/_module.py", line 591, in get_expression
    _, generative_outputs = self.forward(
                            ^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/scvi/module/base/_base_module.py", line 203, in forward
    return _generic_forward(
           ^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/scvi/module/base/_base_module.py", line 739, in _generic_forward
    inference_outputs = module.inference(**inference_inputs, **inference_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/biolord/_module.py", line 366, in inference
    latent_classes = self._inference_attribute_embeddings(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/biolord/_module.py", line 305, in _inference_attribute_embeddings
    latent_i = embedding_(categorical_attribute_dict[attribute_].long())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "biolordenv/lib/python3.11/site-packages/torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

### Version information
```
anndata                  0.10.7
biolord                  0.0.3
lightning                2.1.4
lightning-utilities      0.11.2
pytorch-lightning        2.2.3
scanpy                   1.10.1
scipy                    1.13.0
scvi-tools               1.1.2
torch                    2.3.0
```

**Comment by zoepiran** [comment]
Hi, 

I am afraid we can't reproduce the error, and that it may relate to your local GPU configuration, I see your torch is not a cuda version.

We tested this also in a colab environment, validating also that loading a model on `cpu` loads it to the `cpu` and allows for model prediction, see the notebook [here](https://colab.research.google.com/drive/1LNxILd-jqiDBn-xWiq4SNgQewzmuysyJ?usp=sharing) (for completeness you can download the dummy data used from [here](https://drive.google.com/file/d/1jN1Q_m9s5vkgevQm7yZOVHO6bfRmQrDI/view?usp=sharing)).


```
anndata                  0.10.7
biolord                  0.0.3
lightning                2.1.4
lightning-utilities      0.11.2
pytorch-lightning        2.2.4
scanpy                   1.10.1 
scipy                    1.11.4
scvi-tools               1.1.2
torch                    2.2.1+cu121
```
